name: Test Librus with Selenium

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  test-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 🌐 Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: 📦 Install dependencies
        run: |
          pip install selenium requests
          pip install undetected-chromedriver

      - name: 🧪 Run Selenium Test
        env:
          LIBRUS_USERNAME: ${{ secrets.LIBRUS_USERNAME }}
          LIBRUS_PASSWORD: ${{ secrets.LIBRUS_PASSWORD }}
        run: |
          python test_with_selenium.py

      - name: 💾 Save screenshot on failure
        if: failure()
        run: |
          # Jeśli test nie przejdzie, zapisz screenshot
          echo "Test failed - check logs"