name: Test Librus - Postman Style

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  test-postman:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: |
          pip install requests

      - name: 🌍 Check IP location
        run: |
          echo "=== GitHub Runner IP Info ==="
          curl -s http://ip-api.com/json/ | python -m json.tool
          echo ""
          echo "=== IP Address ==="
          curl -s https://api.ipify.org
          echo ""

      - name: 🧪 Run Postman-style Test
        env:
          LIBRUS_USERNAME: ${{ secrets.LIBRUS_USERNAME }}
          LIBRUS_PASSWORD: ${{ secrets.LIBRUS_PASSWORD }}
        run: |
          python test_like_postman.py

      - name: 🔄 If failed - try with proxy
        if: failure()
        run: |
          echo "Direct connection failed, trying alternatives..."

          # Próba 1: Przez proxy
          export HTTP_PROXY=http://proxy.example.com:8080
          export HTTPS_PROXY=http://proxy.example.com:8080

          # python test_like_postman.py || true

          echo ""
          echo "=== ROZWIĄZANIE ==="
          echo "GitHub Actions jest blokowane przez Librus."
          echo ""
          echo "Opcje:"
          echo "1. Użyj self-hosted runner na własnym komputerze"
          echo "2. Uruchom lokalnie i pushuj wyniki"
          echo "3. Użyj VPS z polskim IP"
          echo ""
          echo "Instrukcja self-hosted runner:"
          echo "https://docs.github.com/en/actions/hosting-your-own-runners"